<?php
    session_start();
    ob_start();
    if(isset($_SESSION['userInfo'])){
        unset($_SESSION['userInfo']);
        header('Location:/login');
        die();
    }
    header('Location:');
    die();
    ob_end_flush();
?>